CREATE DATABASE MyFirstBD;
USE MyFirstBD;
CREATE TABLE Users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT FLOAT NOT NULL
);

CREATE TABLE Services (
    ID_SERVICE INT NOT NULL PRIMARY KEY,
    PRICE FLOAT NOT NULL
);

CREATE TABLE Reservation (
    ID_USER INT NOT NULL ,
    ID_SERVICE INT NOT NULL,
    ID_ORDER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AMOUNT FLOAT NOT NULL
    
);

CREATE TABLE Report (
    ID_USER INT NOT NULL,
    AMOUNT FLOAT NOT NULL,
    ID_SERVICE INT NOT NULL,
    ID_ORDER INT NOT NULL
);


INSERT INTO Services (ID_SERVICE,PRICE) VALUES(1,999);
INSERT INTO Services (ID_SERVICE,PRICE) VALUES(2,1250);
INSERT INTO Services (ID_SERVICE,PRICE) VALUES(3,3333);
 
